image: ghcr.io/my-smart-homes/{arch}-my-smart-homes
build_from:
  aarch64: ghcr.io/my-smart-homes/aarch64-my-smart-homes-base:latest
  armhf: ghcr.io/my-smart-homes/armhf-my-smart-homes-base:latest
  armv7: ghcr.io/my-smart-homes/armv7-my-smart-homes-base:latest
  amd64: ghcr.io/my-smart-homes/amd64-my-smart-homes-base:latest
  i386: ghcr.io/my-smart-homes/i386-my-smart-homes-base:latest
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
cosign:
  base_identity: https://github.com/my-smart-homes/docker/.*
  identity: https://github.com/my-smart-homes/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.title: Home Assistant
  org.opencontainers.image.description: Open-source home automation platform running on Python 3
  org.opencontainers.image.source: https://github.com/my-smart-homes/core
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.my-smart-homes.io/
  org.opencontainers.image.documentation: https://www.my-smart-homes.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
