image: ghcr.io/my-smart-homes/{machine}-homeassistant
build_from:
  aarch64: "ghcr.io/my-smart-homes/aarch64-homeassistant:"
  armv7: "ghcr.io/my-smart-homes/armv7-homeassistant:"
  armhf: "ghcr.io/my-smart-homes/armhf-homeassistant:"
  amd64: "ghcr.io/my-smart-homes/amd64-homeassistant:"
  i386: "ghcr.io/my-smart-homes/i386-homeassistant:"
codenotary:
  signer: notary@my-smart-homes.io
  base_image: notary@my-smart-homes.io
cosign:
  base_identity: https://github.com/my-smart-homes/core/.*
  identity: https://github.com/my-smart-homes/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/my-smart-homes/core
